/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

typedef volatile unsigned int vuint32_t ;
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(vuint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH *(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR *(vuint32_t *)(GPIOA_BASE + 0x08)

#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *(vuint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_CRH *(vuint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR *(vuint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR *(vuint32_t *)(GPIOB_BASE + 0x08)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE + 0x18)


int main(void)
{
	///init pin2 and pin 3 at RCC_APB2ENR with 1 to set the clock for PORTA and PORTB
	RCC_APB2ENR |= 1<<2;
	RCC_APB2ENR |= 1<<3;

	//Init GPIOA
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOB_CRL = 0x0;
	GPIOB_CRH = 0x0;
	//PA1 HighZ input
	GPIOA_CRL |= 1<<6;
	//PA13 HighZ input
	GPIOA_CRH |= 1<<22;
	//PB1 output push-pull
	GPIOB_CRL |= 1<<4;
	GPIOB_CRL &= ~(0x11<<6);
	GPIOB_ODR |= (1<<1); // initialize it with HIGH
	//PB13 output push-pull
	GPIOB_CRH |= 1<<20;
	GPIOB_CRH &= ~(0x11<<22);
	GPIOB_ODR |= (1<<13); // initialize it with hIGH
	while(1)
	{
		if( ! (GPIOA_IDR & (1<<1)) ) // PA1 is pressed
		{
			GPIOB_ODR ^= 1<<1;
			while(! (GPIOA_IDR & (1<<1))); //to make is single pressed
		}

		if( (GPIOA_IDR & (1<<13)) ) // PA13 is pressed
		{
			GPIOB_ODR ^= 1<<13;
			int i;
			for(i = 0; i<100000 ; i++);
		}
	}
}
