/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
//APB1 Bus frequency 16MHZ
//APB2 Bus frequency 8MHZ
//AHB frequency 32 MHZ
//SysClk 32 MHZ
//Use only internal HSI_RC

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

typedef volatile unsigned int vuint32_t ;
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(vuint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR *(vuint32_t *)(RCC_BASE + 0x04)
#define RCC_CR *(vuint32_t *)(RCC_BASE + 0x00)


int main(void)
{
	///initialize pin2 at RCC_APB2ENR with 1 to set the clock for PORTA
	RCC_APB2ENR |= 1<<2;


	//	Bits 21:18 PLLMUL: PLL multiplication factor
	//	These bits are written by software to define the PLL multiplication factor. These bits can be
	//	written only when PLL is disabled.
	//	Caution: The PLL output frequency must not 72 MHz.
	//	0000: PLL input CIOCk x 2
	//	0001: PL-L input x 3
	//	0010: PLL input clock x 4
	//	0011: PLL input Clock X 5
	//	0100: PLL input Clock x 6
	//	0101: PLL input clock x 7
	//	0110: PLL input x 8
	RCC_CFGR |= 0b0110<<18 ;


	//Bits 1:0 SW: System clock switch
	//Set and cleared by software to select SYSCLK source.
	//Set by hardware to force HSI selection when leaving Stop and Standby mode or in case of
	//failure of the HSE oscillator used directly or indirectly as system clock (if the Clock Security
	//System is enabled).
	//00: HSI selected as system clock
	//01: HSE selected as system clock
	//10: PLL selected as system clock
	//11: not allowed
	RCC_CFGR |= 0b10<<0 ;

	//	Bits 10:8 PPREI: APB low-speed prescaler (APBI)
	//	Set and cleared by software to control the division factor of the APB low-speed clock (PCLKI).
	//	oxx: HCLK not divided
	//	100: HCLK divided by 2
	//	101: HCLK divided by 4
	//	110: HCLK divided by 8
	//	111: HCLK divided by 16
	RCC_CFGR |= 0b100 <<8 ;

	//	Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	//	Set and cleared by software to control the division factor of the APB high-speed clock (PCLK2).
	//	Oxx: HCLK not divided
	//	100: HCLK divided by 2
	//	101: HCLK divided by 4
	//	110: HCLK divided by 8
	//	111: HCLK divided by 16
	RCC_CFGR |= 0b101 <<11 ;

	//	Bit 24 PLLON: enable
	//	Set and by software to enable Pl-L.
	//	by hardware when entering aop or 5andby mode. This bit can not be reset if the
	//	PLL clock is used as system clock or is selected to the system clock.
	//	O: PLL OFF
	//	1: PLL ON
	RCC_CR |= 1<<24;


	//Initialize GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
		GPIOA_ODR &= ~(1<<13) ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
	}
}
