/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include "MCAL\GPIO.h"
#include "HAL\LCD\CLCD.h"
#include "HAL\KeyPAD\KPD.h"

int main(void)
{
	CLCD_Init();
	KPD_Init();
	u16 button;
	while(1)
	{
		button = KPD_u8GetPressed();
		if(button != NOTPRESSED)
		CLCD_SendData(button);
	}
	return 0;
}
